### ISSUE TITLE
mirror-client encountering a problem with the tar index

### ISSUE THREAD

**Issue by dcoutts** [well-typed/hackage-security#109]
The mirror-client for the ousl mirror is currently encountering a problem when trying to mirror Ebnf2ps-1.0.15.

It gets to the point where it reads the 00-index.tar.idx and looks up the package.json for that package. But it gets back an apparently bogus offset in the tarball, so that reading at that offset fails. So this would appear to be a bug with the tar index building or reading.

**Comment by edsko** [comment]
Does the mirror client continue at least, just skipping this package?

**Comment by edsko** [comment]
So this indeed due to a bug in the tar index, the same one that caused #112, and the same fix fixes it. The mirror client did not catch this exception, like it does for exceptions when downloading packages, because it occurred at a point where we weren't expecting an exception anymore (because this exception is really an internal error, rather than a temporary--or permanent--problem with the remote server). Just need to restart the mirror client now.

**Comment by edsko** [comment]
Mirror client mirroring away.
