### ISSUE TITLE
'cryptohash' is deprecated

### ISSUE THREAD

**Issue by 23Skidoo** [well-typed/hackage-security#152]
Apparently, the `cryptohash` package has been deprecated in favour of `cryptonite`, and the latest version of `cryptohash` on Hackage is just a thin wrapper for `cryptonite` functions. Given that `cryptonite` is a much larger package, we may want to either set the upper bound in the dependency on `cryptohash` to `0.11.8` or switch to using some other package. Alternatively, we can switch to using `cryptonite` directly. Note that `cryptonite` includes an Ed25519 implementation, which can be used instead of the `ed25519` dependency.

**Comment by hvr** [comment]
Personally, I prefer small and lean packages which do one thing, and do it well rather than big monolithic packages tend to require updates as soon as any part you don't even use needs fixing.

The great thing about @thoughtpolice's [hs-ed25519](https://github.com/thoughtpolice/hs-ed25519) package is that it outshines cryptonite by an order of magnitude in terms attention to detail as can be seen by the amount of work that went into its [documentation](http://hackage.haskell.org/package/ed25519-0.0.5.0/docs/Crypto-Sign-Ed25519.html).

I'd suggest to place an upper bound on `cryptohash` for now, and consider a more focused alternative to cryptonite, as we really only need an efficient sha256 implementation, rather than a fully fledged crypto package with several algorithms and ciphers...

**Comment by 23Skidoo** [comment]
I second that.

**Comment by hvr** [comment]
@edsko @dcoutts @23Skidoo I stripped out the sha256 functionality from `cryptohash` into a new package http://hackage.haskell.org/package/cryptohash-sha256-0.11.7.1 with truly minimal package dependencies. The implementation is almost exactly the one that was used in `cryptohash-0.11.7`.

I've created #153 as proof of concept

**Comment by 23Skidoo** [comment]
@hvr Thanks!

**Comment by dcoutts** [comment]
Now using cryptohash-sha256
